[package]
name = "strigoi"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.8.0"
ariadne = "0.1.5"
walkdir = "2.3.2"
clap = { version = "3.2.20", features = ["cargo", "derive"] }
dbg-pls = { version = "0.3.3", features = ["colors", "derive"] }